#!/bin/bash

# Guide de lancement manuel de Nav2

echo "════════════════════════════════════════════════════"
echo "   GUIDE NAVIGATION NAV2 - Lancement Manuel"
echo "════════════════════════════════════════════════════"
echo ""
echo "Suivez ces étapes dans des terminaux séparés :"
echo ""
echo "TERMINAL 1 - Gazebo :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 launch my_robot_controller launch_sim.launch.py"
echo ""
echo "TERMINAL 2 - Map Server :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 run nav2_map_server map_server --ros-args -p yaml_filename:=~/my_robot_map2.yaml -p use_sim_time:=true"
echo ""
echo "TERMINAL 3 - AMCL (Localisation) :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 run nav2_amcl amcl --ros-args -p use_sim_time:=true --remap /odom:=/diff_cont/odom"
echo ""
echo "TERMINAL 4 - Nav2 Lifecycle Manager :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 run nav2_lifecycle_manager lifecycle_manager --ros-args -p use_sim_time:=true -p autostart:=true -p node_names:=[map_server,amcl]"
echo ""
echo "TERMINAL 5 - Controller Server :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 launch nav2_bringup controller.launch.py use_sim_time:=true params_file:=src/my_robot_controller/config/nav2_params.yaml"
echo ""
echo "TERMINAL 6 - Planner Server :"
echo "  cd ~/ROS2_Project && source install/setup.bash"
echo "  ros2 launch nav2_bringup planner.launch.py use_sim_time:=true params_file:=src/my_robot_controller/config/nav2_params.yaml"
echo ""
echo "════════════════════════════════════════════════════"
echo "   OU UTILISEZ LE SCRIPT AUTOMATIQUE CI-DESSOUS"
echo "════════════════════════════════════════════════════"
