slam_toolbox:
  ros__parameters:

    # ===== GENERAL =====
    use_sim_time: true
    mode: mapping

    # ===== FRAMES =====
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: scan

    # ===== TIMING =====
    transform_publish_period: 0.05
    map_update_interval: 2.0

    # ===== SCAN MATCHING =====
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    # ===== RANGE =====
    max_laser_range: 20.0
    min_laser_range: 0.2

    # ===== LOOP CLOSURE =====
    do_loop_closing: true
    loop_search_maximum_distance: 3.0

    # ===== MATCHING QUALITY =====
    use_scan_matching: true
    use_scan_barycenter: true

    # ===== OPTIMIZATION =====
    ceres_solver_plugin: ceres_solver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    # ===== CORRELATION =====
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # ===
